# Visualize .mat format data (array)  
 * MATLAB .mat files contain internal struct, use numpy to unpack.  
 * scipy installed in ecg env not base env  
 * conda activate ecg
 * row labels:(I, II, III, aVR, aVL, aVF, V1, V2, V3, V4, V5, V6) 

Date: March 25, 2026 Wed 6pm.  
Subject: Jason's ECG Project  
Author:  Jennifer Yoon

In [1]:
import scipy.io
import numpy as np 
print(scipy.__version__)

1.15.3


In [4]:
# PTB-XL g1 data, augmented noise added, already downsample and rescaled data.  
path = "./data_trained/ptbxl_aug_sample/"
file = "HR00001_aug.mat" 
filename = path + file  
print(filename)

./data_trained/ptbxl_aug_sample/HR00001_aug.mat


In [5]:
# PTB-XL g1 data, downsampled to 125 hertz and scaled to millivolts (+1.0 to -1.0 float)
path2 = "./data_trained/ptbxl_dwmv_sample/"
file2 = "HR00001.mat"
filename2 = path2 + file2  
print(filename2)

./data_trained/ptbxl_dwmv_sample/HR00001.mat


### Augmented data sample:  
Verify that sampling rate matches what will be used in inference model run.  
Should be 125 hertz and millivolts amplitude. 

In [6]:
# Load the .mat file
mat_data = scipy.io.loadmat(filename, struct_as_record=False, squeeze_me=True)
print(mat_data, type(mat_data))

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Tue Jul  8 21:05:52 2025', '__version__': '1.0', '__globals__': [], 'val': array([[-0.02621623, -0.02443786, -0.01671192, ...,  0.15230843,
         0.15452712,  0.15676619],
       [ 0.01543631,  0.01442761,  0.01516417, ...,  0.24308493,
         0.24442388,  0.24574892],
       [ 0.01906308,  0.01924605,  0.01521826, ..., -0.00107935,
        -0.00153224, -0.0019854 ],
       ...,
       [-0.09860802, -0.09808222, -0.09300059, ...,  0.09953339,
         0.09931932,  0.09911253],
       [-0.08021434, -0.08029699, -0.07449221, ...,  0.14693814,
         0.14666685,  0.14639804],
       [-0.13786779, -0.13816722, -0.13245935, ...,  0.11201525,
         0.112222  ,  0.11243639]], shape=(12, 1250))} <class 'dict'>


In [7]:
# Access the struct 
data = mat_data['val']

# Show elements of data (ndarray type)
print('first 5 elements: \n', data[:5])
print('length of row 0:', len(data[0]))

first 5 elements: 
 [[-0.02621623 -0.02443786 -0.01671192 ...  0.15230843  0.15452712
   0.15676619]
 [ 0.01543631  0.01442761  0.01516417 ...  0.24308493  0.24442388
   0.24574892]
 [ 0.01906308  0.01924605  0.01521826 ... -0.00107935 -0.00153224
  -0.0019854 ]
 [ 0.05921875  0.06010482  0.05712375 ... -0.20026247 -0.20121586
  -0.2021712 ]
 [-0.05334368 -0.0531345  -0.04783862 ...  0.10085502  0.10018936
   0.09952579]]
length of row 0: 1250


In [ ]:
# Check units range is +1 to -1.0 (millivolts)
for i in range(12): 
    print(f"min row {i}: {min(data[i])}, max row {i}: {max(data[i])}") 
    next 
# row 7 is slightly beyong -1.0. OK.     
# row labels:(I, II, III, aVR, aVL, aVF, V1, V2, V3, V4, V5, V6) 

min row 0: -0.29703068550109624, max row 0: 0.7026812573723225
min row 1: -0.2189861692441871, max row 1: 0.43748357585946385
min row 2: -0.3626394907326731, max row 2: 0.15263878550695603
min row 3: -0.5139262971886159, max row 3: 0.2012885652326708
min row 4: -0.16820150292181463, max row 4: 0.5444792725524583
min row 5: -0.13406817188232775, max row 5: 0.17292344123061898
min row 6: -0.9659958679439291, max row 6: 0.29069498906864943
min row 7: -1.0663435590883301, max row 7: 0.4063930845298544
min row 8: -0.8349899573091958, max row 8: 0.6761624914933656
min row 9: -0.41608321039027985, max row 9: 0.6137171520825189
min row 10: -0.12872168734532619, max row 10: 0.6338064349541354
min row 11: -0.19064353505323797, max row 11: 0.5947063863035453


**AI note: The Formatting Pattern: F-Strings**  
The line in your cell is (or should be) a Formatted String Literal, commonly called an f-string.

The Syntax: It is defined by placing an f or F before the opening quotation mark: f"...".

The Mechanism: Anything placed inside curly braces { } is treated as Python code. Python evaluates that code and converts the result into a string.

### dwmv sample verify   
PTB-XL g1 data, down sample to 125 hertz, and unit scaled to millivolts


In [16]:
# Load the .mat file
mat_data2 = scipy.io.loadmat(filename2, struct_as_record=False, squeeze_me=True)
print(mat_data2, type(mat_data2))

{'__header__': b'MATLAB 5.0 MAT-file Platform: posix, Created on: Thu Jun 26 18:46:44 2025', '__version__': '1.0', '__globals__': [], 'val': array([[-0.115, -0.115, -0.109, ...,  0.21 ,  0.21 ,  0.21 ],
       [-0.05 , -0.05 , -0.048, ...,  0.205,  0.205,  0.205],
       [ 0.065,  0.065,  0.061, ..., -0.005, -0.005, -0.005],
       ...,
       [-0.035, -0.035, -0.03 , ...,  0.185,  0.185,  0.185],
       [-0.035, -0.035, -0.029, ...,  0.17 ,  0.17 ,  0.17 ],
       [-0.075, -0.075, -0.069, ...,  0.18 ,  0.18 ,  0.18 ]],
      shape=(12, 1250))} <class 'dict'>


In [19]:
# Access the struct 
data2 = mat_data2['val']

# Show elements of data (ndarray type)
print('first 5 elements: \n', data2[:5])
print('length of row 0:', len(data2[0]))

first 5 elements: 
 [[-0.115 -0.115 -0.109 ...  0.21   0.21   0.21 ]
 [-0.05  -0.05  -0.048 ...  0.205  0.205  0.205]
 [ 0.065  0.065  0.061 ... -0.005 -0.005 -0.005]
 [ 0.082  0.082  0.078 ... -0.207 -0.207 -0.207]
 [-0.09  -0.09  -0.085 ...  0.107  0.107  0.107]]
length of row 0: 1250


In [18]:
# Check units range is +1 to -1.0 (millivolts)
for i in range(12): 
    print(f"min row {i}: {min(data2[i])}, max row {i}: {max(data2[i])}") 
    next 

min row 0: -0.21, max row 0: 0.671
min row 1: -0.145, max row 1: 0.448
min row 2: -0.356, max row 2: 0.15
min row 3: -0.536, max row 3: 0.177
min row 4: -0.158, max row 4: 0.513
min row 5: -0.1, max row 5: 0.17
min row 6: -0.721, max row 6: 0.157
min row 7: -1.404, max row 7: 0.428
min row 8: -0.614, max row 8: 0.57
min row 9: -0.313, max row 9: 0.575
min row 10: -0.095, max row 10: 0.611
min row 11: -0.155, max row 11: 0.6


In [ ]:
# row 7 is beyong -1.0, it is -1.404.  
# Do these get cut off when used in model? I think so.  