<a href="https://colab.research.google.com/github/JennEYoon/ECG-transform/blob/main/demo_2026/predict_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Prediction Model, v2  
filename: predict_v2.ipynb, on Colab  
Part of "demo_2026" folder, sub-topic  
Owner: Jennnifer Yoon   
Date: March 21, 2026 Saturday - March 22, 2026 Sunday    

***input files***  
*.npy, *.hea  

***output files***  
predict_v13.pth
*.png
*.csv - controller file, peak detect  

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os

### 0. Fetch data, from URL path

In [6]:
# Simplest code for URL fetch one numpy file.
# Replace with S3, GitHub, or Website URL
!wget http://datasciy.com/data_predict/ecg_4canales_1.npy

data = np.load('ecg_4canales_1.npy')
print(data)
print(str(data))

--2026-03-22 03:52:18--  http://datasciy.com/data_predict/ecg_4canales_1.npy
Resolving datasciy.com (datasciy.com)... 52.217.166.141, 52.217.132.5, 52.216.62.149, ...
Connecting to datasciy.com (datasciy.com)|52.217.166.141|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 480128 (469K) [application/octet-stream]
Saving to: ‘ecg_4canales_1.npy.1’

ecg_4canales_1.npy. 100%[===================>] 468.88K  --.-KB/s    in 0.1s    

2026-03-22 03:52:18 (3.64 MB/s) - ‘ecg_4canales_1.npy.1’ saved [480128/480128]

[[ 0.55770783 -0.56275764 -0.56965174  0.15444015]
 [ 0.57164869 -0.56574271 -0.58576167  0.19121162]
 [ 0.53613618 -0.62842928 -0.59950249  0.16602317]
 ...
 [ 0.47602814 -0.71191218 -0.54462873  0.06278527]
 [ 0.49735258 -0.69470405 -0.60124245 -0.0309362 ]
 [-0.7715239  -1.         -1.         -0.78496805]]
[[ 0.55770783 -0.56275764 -0.56965174  0.15444015]
 [ 0.57164869 -0.56574271 -0.58576167  0.19121162]
 [ 0.53613618 -0.62842928 -0.59950249  0.16602317]
 

In [10]:
!wget http://datasciy.com/data_predict/ecg_4canales_1.npy
data1 = np.load('ecg_4canales_1.npy')
print(data1)

!wget http://datasciy.com/data_predict/ecg_4canales_2.npy
data2 = np.load('ecg_4canales_2.npy')
print(data2)

!wget http://datasciy.com/data_predict/ecg_4canales_3.npy
data3 = np.load('ecg_4canales_3.npy')
print(data3)

!wget http://datasciy.com/data_predict/ecg_4canales_4.npy
data4 = np.load('ecg_4canales_4.npy')
print(data4)


--2026-03-22 04:21:12--  http://datasciy.com/data_predict/ecg_4canales_1.npy
Resolving datasciy.com (datasciy.com)... 54.231.202.245, 52.216.214.29, 54.231.196.181, ...
Connecting to datasciy.com (datasciy.com)|54.231.202.245|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 480128 (469K) [application/octet-stream]
Saving to: ‘ecg_4canales_1.npy.3’

ecg_4canales_1.npy. 100%[===================>] 468.88K  --.-KB/s    in 0.1s    

2026-03-22 04:21:13 (3.36 MB/s) - ‘ecg_4canales_1.npy.3’ saved [480128/480128]

[[ 0.55770783 -0.56275764 -0.56965174  0.15444015]
 [ 0.57164869 -0.56574271 -0.58576167  0.19121162]
 [ 0.53613618 -0.62842928 -0.59950249  0.16602317]
 ...
 [ 0.47602814 -0.71191218 -0.54462873  0.06278527]
 [ 0.49735258 -0.69470405 -0.60124245 -0.0309362 ]
 [-0.7715239  -1.         -1.         -0.78496805]]
--2026-03-22 04:21:13--  http://datasciy.com/data_predict/ecg_4canales_2.npy
Resolving datasciy.com (datasciy.com)... 54.231.202.245, 52.216.214.29, 54.

### I. Load data

### II. Plot data, min, max average

### III. Rescale, 125 hertz, millivolts

### IV. Split into single beat windows

### V. upload trained model, class list (labels)  

### VI. Run eval()

### VII. Results table, figures. Export to folder.